FROM oven/bun:1-slim

WORKDIR /app

COPY package.json bun.lockb ./
RUN bun install --production

COPY . .

# GIT_COMMIT is generated by CI before docker build (see .github/workflows/deploy.yml)
RUN test -f GIT_COMMIT || echo "unknown" > GIT_COMMIT

ENV PORT=5000
ENV STORAGE_PATH=/app/storage

EXPOSE 5000

CMD ["bun", "run", "src/serve.ts"]
