export const tagTransformations = {
  "Charakter/Figur": ["Charakter", "Figur"],
  "Direction Games": ["Direction"],
  "Improv Games": ["game"],
  "Warm-ups": ["warmup"],
  "Pantomime Übungen": ["Pantomime"],
  Storytelling: ["Storytelling"],
  Gefühlsspiele: ["Emotion"],
  "Gefühle - Übungen": ["Emotion", "Übung"],
  "Angebot/Annahme": ["Angebot", "Annahme"],
  "Musik und Gesang": ["Musik", "Gesang"],
  Singen: ["Gesang"],
  "Music Games": ["Music"],
  "chain games": ["chain games"],
  status: ["status"],
  switches: ["switches"],
  Vertrauensübungen: ["trust"],
  attention: ["attention"],
  freshman: ["freshman"],
  calm: ["calm"],
  energetic: ["energetic"],
  "Slapstick-Hektik-Action": ["Slapstick"],
  "Spiele im ImprotheaterKettenspiele": ["Spiel", "Kettenspiele"],
  "Spiele mit Gegenständen": ["Gegenstände"],
  "Slapstick-Bustle-Action": ["Slapstick"],
  "Aktion & Reaktion": ["Aktion", "Reaktion"],
  "Körperkontakt und Berührung": ["Körperkontakt", "Berührung"],
  "Spiele im ImprotheaterMusikspiele": ["Spiel", "Musik"],
  "Spiele im ImprotheaterKörperkontakt und Berührung": [
    "Spiel",
    "Körperkontakt",
    "Berührung",
  ],
  Regiespiele: ["Regie"],
  "Spiele im ImprotheaterMusik und Gesang": ["Spiel", "Musik", "Gesang"],
  Impuls: ["Impuls"],
  Schnelligkeit: ["Schnelligkeit"],
  Impulse: ["Impulse"],
  Speed: ["Speed"],
  "Spiele im ImprotheaterReden": ["Spiel", "Reden"],
  Erzählen: ["Erzählen"],
  "Spiele im ImprotheaterSpiele mit Gegenständen": ["Gegenstände"],
  "Spiele im ImprotheaterErzählen": ["Spiel", "Erzählen"],
  Paarbildung: ["Paare"],
  Gruppen: ["Gruppe"],
  Langformen: ["longform"],
  longform: ["longform"],
  "Spiele im ImprotheaterRegiespiele": ["Spiel", "Regie"],
  "Spiele im ImprotheaterZuschauer auf der Bühne": [
    "Spiel",
    "Zuschauer auf der Bühne",
  ],
  "Spiele im ImprotheaterReplays": ["Spiel", "Replays"],
  "Spiele im ImprotheaterSlapstick-Hektik-Action": ["Spiel", "Slapstick"],
  Zuschauer: ["Zuschauer"],
  Perception: ["Perception"],
  "Spiele im ImprotheaterSonstige": ["Spiel", "Sonstige"],
  Sonstiges: ["Sonstige"],
  "Improv Exercises": ["exercise"],
  "Finding Game": ["Search Game"],
  Showformen: ["show"],
  Gefühle: ["Emotion"],
  "Kennenlernen - Namensspiele": ["Kennenlernen", "Namensspiele"],
  "Stimme - Gesang": ["Stimme", "Gesang"],
  "Raumlauf-Bewegung": ["Raumlauf", "Bewegung"],
  "Icebreaker Games": ["Icebreaker"],
  Kennenlernspiele: ["icebreaker"],
  "Physicalness - Movement": ["Physicalness", "Movement"],
  "AufwärmspieleRaumlauf-Bewegung": ["Aufwärmspiel", "Raumlauf", "Bewegung"],
  Akzeptieren: ["Annahme"],
  "Action Reaction": ["Action", "Reaction"],
  "Action & Reaction": ["Action", "Reaction"],
  ÜbungenAssoziieren: ["Übung", "Assoziieren"],
  "ÜbungenAngebot/Annahme": ["Übung", "Angebot", "Annahme"],
  ÜbungenAkzeptieren: ["Übung", "Annahme"],
  Begriffserklärungen: [],
  ÜbungenAtmung: ["Übung", "Atmung"],
  "ÜbungenMusik und Gesang": ["Übung", "Musik", "Gesang"],
  Expression: ["Expression"],
  ÜbungenAusdruck: ["Übung", "Ausdruck"],
  "ÜbungenPantomime Übungen": ["Übung", "Pantomime"],
  ÜbungenWahrnehmung: ["Übung", "Wahrnehmung"],
  "ÜbungenCharakter/Figur": ["Übung", "Charakter", "Figur"],
  ÜbungenGedächtnis: ["Übung", "Gedächtnis"],
  ÜbungenImpuls: ["Übung", "Impuls"],
  "ÜbungenGefühle - Übungen": ["Übung", "Emotion", "Übung"],
  ÜbungenGruppe: ["Übung", "Gruppe"],
  ÜbungenSonstiges: ["Übung", "Sonstige"],
  "Tanz/Choreographie": ["Tanz", "Choreographie"],
  "dialogue form": ["dialogue"],
  "Dialogue Form": ["dialogue"],
  "dialogue forms": ["dialogue"],
  Dialogformen: ["dialogue"],
  "direction games": ["Direction"],
  "Im Kreis": ["circle"],
  "Aktion und Reaktion - Übungen": ["Aktion", "Reaktion", "Übung"],
  "Emotion Games": ["Emotion"],
};
