export const tagTransformations = {
  Buchstabenspiele: ["Buchstabenspiele"],
  game: ["game"],
  Alphabet: ["Alphabet"],
  Aufmerksamkeit: ["Aufmerksamkeit"],
  Anfänger: ["Anfänger"],
  "Letter Games": ["Letter Games"],
  Fortgeschritten: ["Fortgeschritten"],
  Talking: ["Talking"],
  Speech: ["Speech"],
  "Dialogue Form": ["Dialogue Form"],
  "Zuschauer auf der Bühne": ["Zuschauer auf der Bühne"],
  "Charakter/Figur": ["Charakter", "Figur"],
  exercise: ["exercise"],
  Ratespiele: ["Ratespiele"],
  Kettenspiele: ["Kettenspiele"],
  Regie: ["Regie"],
  Switches: ["Switches"],
  Teamplay: ["Teamplay"],
  Character: ["Character"],
  "Direction Games": ["Direction"],
  Profi: ["Profi"],
  "Improv Games": ["game"],
  Dialogformen: ["Dialogformen"],
  Reden: ["Reden"],
  Körperlichkeit: ["Körperlichkeit"],
  Sonstige: ["Sonstige"],
  Gromolo: ["Gromolo"],
  "Warm-ups": ["Warm-ups"],
  warmup: ["warmup"],
  "Pantomime Übungen": ["Pantomime Übungen"],
  Storytelling: ["Storytelling"],
  Gefühlsspiele: ["Gefühlsspiele"],
  "Gefühle - Übungen": ["Gefühle", "Übung"],
  Gefühle: ["Gefühle"],
  "Emotion Games": ["Emotion Games"],
  Replays: ["Replays"],
  Replay: ["Replay"],
  Musikspiele: ["Musikspiele"],
  "Chain Games": ["Chain Games"],
  "Angebot/Annahme": ["Angebot", "Annahme"],
  "Musik und Gesang": ["Musik", "Gesang"],
  Musik: ["Musik"],
  Singen: ["Gesang"],
  "Music Games": ["Music Games"],
  "chain games": ["chain games"],
  status: ["status"],
  switches: ["switches"],
  attention: ["attention"],
  freshman: ["freshman"],
  calm: ["calm"],
  energetic: ["energetic"],
  "Slapstick-Hektik-Action": ["Slapstick-Hektik-Action"],
  Slapstick: ["Slapstick"],
  "Spiele im ImprotheaterKettenspiele": ["Spiel", "Kettenspiele"],
  "Spiele mit Gegenständen": ["Gegenstände"],
  Gegenstände: ["Gegenstände"],
  Objects: ["Objects"],
  "Slapstick-Bustle-Action": ["Slapstick-Bustle-Action"],
  "Aktion & Reaktion": ["Aktion", "Reaktion"],
  "Körperkontakt und Berührung": ["Körperkontakt", "Berührung"],
  "Spiele im ImprotheaterMusikspiele": ["Spiel", "Musikspiele"],
  "Spiele im ImprotheaterKörperkontakt und Berührung": [
    "Spiel",
    "Körperkontakt",
    "Berührung",
  ],
  "Schwarz auf Weiß": ["Schwarz auf Weiß"],
  Regiespiele: ["Regie"],
  "Spiele im ImprotheaterMusik und Gesang": ["Spiel", "Musik", "Gesang"],
  Synchro: ["Synchro"],
  Dubbing: ["Dubbing"],
  "Guessing Games": ["Guessing Games"],
  Impuls: ["Impuls"],
  Schnelligkeit: ["Schnelligkeit"],
  Impulse: ["Impulse"],
  Speed: ["Speed"],
  "Spiele im ImprotheaterReden": ["Spiel", "Reden"],
  Erzählen: ["Erzählen"],
  "Spiele im ImprotheaterSpiele mit Gegenständen": ["Gegenstände"],
  "Spiele im ImprotheaterErzählen": ["Spiel", "Erzählen"],
  Assoziieren: ["Assoziieren"],
  Konzentration: ["Konzentration"],
  Paarbildung: ["Paare"],
  Gruppen: ["Gruppe"],
  Gruppe: ["Gruppe"],
  Multitasking: ["Multitasking"],
  Paare: ["Paare"],
  Wahrnehmung: ["Wahrnehmung"],
  Zuhören: ["Zuhören"],
  Basisinformationen: ["Basisinformationen"],
  Langformen: ["Langformen"],
  longform: ["longform"],
  "Improv Forms": ["Improv Forms"],
  show: ["show"],
  "Spiele im ImprotheaterRegiespiele": ["Spiel", "Regie"],
  "Spiele im ImprotheaterZuschauer auf der Bühne": [
    "Spiel",
    "Zuschauer auf der Bühne",
  ],
  "Audience on stage": ["Audience on stage"],
  "Spiele im ImprotheaterReplays": ["Spiel", "Replays"],
  Texte: ["Texte"],
  "In Black and White": ["In Black and White"],
  "Spiele im ImprotheaterSlapstick-Hektik-Action": [
    "Spiel",
    "Slapstick-Hektik-Action",
  ],
  Zuschauer: ["Zuschauer"],
  Perception: ["Perception"],
  "Spiele im ImprotheaterSonstige": ["Spiel", "Sonstige"],
  Sonstiges: ["Sonstige"],
  Other: ["Other"],
  Genreliste: ["Genreliste"],
  "Improv Exercises": ["Improv Exercises"],
  "Finding Game": ["Finding Game"],
  Showformen: ["show"],
  Status: ["Status"],
  advanced: ["advanced"],
  "team play": ["team play"],
  "Im Kreis": ["Im Kreis"],
  "Kennenlernen - Namensspiele": ["Kennenlernen", "Namensspiele"],
  Group: ["Group"],
  Ausdruck: ["Ausdruck"],
  Gedächtnis: ["Gedächtnis"],
  circle: ["circle"],
  Reimen: ["Reimen"],
  Rhyming: ["Rhyming"],
  "Stimme - Gesang": ["Stimme", "Gesang"],
  "Raumlauf-Bewegung": ["Raumlauf", "Bewegung"],
  "Icebreaker Games": ["Icebreaker Games"],
  Kennenlernspiele: ["Kennenlernspiele"],
  "Physicalness - Movement": ["Physicalness", "Movement"],
  Raumlauf: ["Raumlauf"],
  Räume: ["Räume"],
  "AufwärmspieleRaumlauf-Bewegung": ["Aufwärmspiele", "Raumlauf", "Bewegung"],
  Association: ["Association"],
  Fokus: ["Fokus"],
  Akzeptieren: ["Annahme"],
  Accepting: ["Accepting"],
  "Action Reaction": ["Action", "Reaction"],
  "Action & Reaction": ["Action", "Reaction"],
  pro: ["pro"],
  "Aktion und Reaktion - Übung": ["Aktion", "Reaktion", "Übung"],
  Listening: ["Listening"],
  ÜbungenAssoziieren: ["Übung", "Assoziieren"],
  "ÜbungenAngebot/Annahme": ["Übung", "Angebot", "Annahme"],
  ÜbungenAkzeptieren: ["Übung", "Annahme"],
  Begriffserklärungen: [],
  Atmung: ["Atmung"],
  ÜbungenAtmung: ["Übung", "Atmung"],
  "ÜbungenMusik und Gesang": ["Übung", "Musik", "Gesang"],
  Expression: ["Expression"],
  ÜbungenAusdruck: ["Übung", "Ausdruck"],
  "ÜbungenPantomime Übungen": ["Übung", "Pantomime Übungen"],
  ÜbungenWahrnehmung: ["Übung", "Wahrnehmung"],
  "ÜbungenCharakter/Figur": ["Übung", "Charakter", "Figur"],
  Dramaturgie: ["Dramaturgie"],
  Kreis: ["Kreis"],
  ÜbungenGedächtnis: ["Übung", "Gedächtnis"],
  ÜbungenImpuls: ["Übung", "Impuls"],
  "ÜbungenGefühle - Übungen": ["Übung", "Gefühle", "Übung"],
  ÜbungenGruppe: ["Übung", "Gruppe"],
  Vertrauensübungen: ["Vertrauensübungen"],
  pairs: ["pairs"],
  ÜbungenSonstiges: ["Übung", "Sonstige"],
  "Tanz/Choreographie": ["Tanz", "Choreographie"],
  "dialogue form": ["dialogue form"],
  "direction games": ["Direction"],
  talking: ["talking"],
  storytelling: ["storytelling"],
  "Improv Groups": ["Improv Groups"],
  Organisation: ["Organisation"],
  "Rules & Tips": ["Rules & Tips"],
};
